[package]
name = "reimpl-jq-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
argopt = "0.1.1"
json = "0.12.4"
jsonpath = "0.1.1"